# name: Check Device Status

# on:
#   schedule:
#     - cron: '0 * * * *'  # Run every hour
#   workflow_dispatch:  # Allow manual trigger

# jobs:
#   check-devices:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '18'

#     - name: Install dependencies
#       run: npm ci

#     - name: Run device status checker
#       env:
#         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#         API_TOKEN: ${{ secrets.API_TOKEN }}
#       run: node index.js
